apiVersion: batch/v1
kind: Job
metadata:
  name: early-cpe-23
  namespace: msc24chrisproject
spec:
  backoffLimit: 0
  template:        
    metadata:
      name: early-cpe-23
    spec:
      containers:
      - name: training-container  
        image: chris114abraham/masters:early_combine
        imagePullPolicy: Always
        command: ["python", "training.py", "con","20","10","early-cpe-23", "0.0005"]
        resources:
          requests:
            cpu: "2000m" 
            memory: "8Gi"
            nividia.com/gpu: 1
          limits:
            cpu: "10000m" 
            memory: "50Gi"
            nividia.com/gpu: 1
        volumeMounts:
        - mountPath: /nfs
          name: nfs-access
        env:
        - name: TRANSFORMERS_CACHE
          value: "/nfs"
      volumes:
      - name: nfs-access
        persistentVolumeClaim: 
          claimName: msc24chrisvol1claim 
      nodeSelector:
        node-role.ida/gpua6000: "true"
      restartPolicy: Never
      