apiVersion: batch/v1
kind: Job
metadata:
  name: training
  namespace: msc24chrisproject
spec:
  backoffLimit: 0
  template:        
    metadata:
      name: trainingv4
    spec:
      containers:
      - name: training-container  
        image: chris114abraham/masters:latest
        command: ["python", "main.py", "10","5","first_model"]
        resources:
          requests:
            cpu: "5000m" 
            memory: "10Gi"
          limits:
            cpu: "10000m" 
            memory: "100Gi"
        volumeMounts:
        - mountPath: /nfs
          name: nfs-access
        env:
        - name: TRANSFORMERS_CACHE
          value: "/nfs"
      volumes:
      - name: nfs-access
        persistentVolumeClaim: 
          claimName: msc24chrisvol1claim 
      restartPolicy: Never
