apiVersion: batch/v1
kind: Job
metadata:
  name: cpe-model
  namespace: msc24chrisproject
spec:
  backoffLimit: 0
  template:        
    metadata:
      name: cpe-model
    spec:
      containers:
      - name: training-container  
        image: chris114abraham/masters:combine
        imagePullPolicy: Always
        command: ["python", "combined_model.py", "con-ped-ext","10","20","0.0005","cpe_model_final","0.3"]
        resources:
          requests:
            cpu: "5000m" 
            memory: "10Gi"
          limits:
            cpu: "10000m" 
            memory: "100Gi"
        volumeMounts:
        - mountPath: /nfs
          name: nfs-access
        env:
        - name: TRANSFORMERS_CACHE
          value: "/nfs"
      volumes:
      - name: nfs-access
        persistentVolumeClaim: 
          claimName: msc24chrisvol1claim 
      restartPolicy: Never
